variable "filename"{
	default="/home/ubuntu/terraform-course/terraform_variables/devops-automated.txt"
}

variable "content"{
	default="This is autogenerated from a variable."
}

variable "megha_trainer" {}

variable  "content_map" {
	type = map
	default = {
		 "content1" = "This is cool content1"
		 "content2" = "This is cooler content2"
	}
}

variable "file_list" {
	type = list
	default = ["/home/ubuntu/terraform-course/terraform_variables/file1.txt","/home/ubuntu/terraform-course/terraform_docker/terraform_va			riables/file2.txt"]
}

variable  "aws_ec2_object" {
	type = object({
		name = string
		instance = number
		keys = list(string)
		ami = string
	})
	default = {
		name = "test_ec2_instance"
		instance = 4
		keys = ["Awskeypair.pem"]
		ami = "ubunutu- aa12323"
}

}

variable "no_of_students"{}
